server:
  port: 8081
  error:
    include-message: always
#    Database Mysql
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/tracker
    password: '12345'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    Trello API
trello:
  api:
    endpoint:
      prod: https://api.trello.com/1
  app:
    key: 27adb151059841d76aa93b2bee1c6c44
    token: 5245fec2bc7b98a3ffe1d8cf168597550aa6210ac342a8244a2ccd2a68f9712f